run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  # Enables skipping of directories:
  # - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  # Default: true
  skip-dirs-use-default: false
  modules-download-mode: mod
  allow-parallel-runners: true
  go: '1.18'
